@url = http://localhost:5244
@reservationId = 1

@reservationId = 00000000-0000-0000-0000-000000000001
@parkingSpotId = 00000000-0000-0000-0000-000000000001

GET {{url}}

### 
GET {{url}}/parking-spots

###

GET {{url}}/parking-spots/{{reservationId}}\

###
POST {{url}}/parking-spots/{{parkingSpotId}}/reservationsvehicle
Content-Type: application/json

{ 
  "EmployeeName" : "John Doe",
  "licenseplate" : "xyz111",
  "capacity" : 1
  "date" : "2024-12-08"
}

###
POST {{url}}/reservations/cleaning
Content-Type: application/json

{
  "date" : "2024-12-08"
}


###
PUT {{url}}/reservations/{{reservationId}}
Content-Type: application/json

{
  "LicensePlate": "ABC"
}

###
DELETE {{ulr}}/reservations/{{reservationId}}
