@url = http://localhost:5244
@reservationId = 1

@reservationId = 00000000-0000-0000-0000-000000000001
@parkingSpotId = 00000000-0000-0000-0000-000000000001

GET {{url}}

### 
GET {{url}}/reservations

###

GET {{url}}/reservations/{{reservationId}}\

###
POST {{url}}/reservations/vehicle
Content-Type: application/json

{
  "parkingSpotId" : "{{parkingSpotId}}}",
  "capacity" : 1
  "EmployeeName" : "John Doe",
  "licenseplate" : "xyz111",
  "date" : "2024-12-08"
}

###
POST {{url}}/reservations/cleaning
Content-Type: application/json

{
  "date" : "2024-12-08"
}


###
PUT {{url}}/reservations/{{reservationId}}
Content-Type: application/json

{
  "LicensePlate": "ABC"
}

###
DELETE {{ulr}}/reservations/{{reservationId}}
